apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: skylt/rabbitmq-example-sender
    context: .
    docker:
      dockerfile: docker/Dockerfile.sender
  - image: skylt/rabbitmq-example-receiver
    context: .
    docker:
      dockerfile: docker/Dockerfile.receiver
deploy:
  kubectl:
    manifests:
    - k8s-*.yaml
